### PR TITLE
allow spatie/macroable v2

### PR DESCRIPTION
**Pull request by Nielsvanpach**

### CODE REVIEW

**Comment by vonec** [comment]
is this released yet ?

**Comment by Nielsvanpach** [comment]
Yes it is: https://github.com/spatie/ray/releases

**Comment by vonec** [comment]
this is breaking my current laravel 8 application running on php 7.4

``During class fetch: Uncaught ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in C:\xampp\htdocs\MYAPP\vendor\spatie\macroable\src\Macroable.php:14``

**Comment by Nielsvanpach** [comment]
spatie/macroable v2 does not support PHP 7. Make sure you use v1 in that case.

**Pull request merged**
