### PR TITLE
Go module docs

### PR DESCRIPTION
**Pull request by octoper**
This PR adds docs for [octoper/go-ray](https://github.com/octoper/go-ray) module.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you!

**Comment by freekmurze** [comment]
I don't know Go that well, but would it be possible avoiding having to the double Ray: `ray.Ray()`, would be much nicer if users would be able to call `ray()` or `Ray()`, but I don't know if that's possible in the language.

**Comment by petaki** [comment]
@freekmurze First of all, thanks for the awesome Ray app. I've been using it every day since I bought it.

A few days ago I also started a Go adapter (https://github.com/petaki/go-ray), but this is a more complete lib. Thanks @octoper!

I created a `DefaultRay` instance based on the official `net/http` lib `DefaultClient` idea and I created a wrapper method around it.

Code:

- https://github.com/petaki/go-ray/blob/master/ray.go#L22
- https://github.com/petaki/go-ray/blob/master/ray.go#L165

After this, I can call the methods on the namespace:

```go
ray.Send()
ray.Pass()
ray.Color()
ray.Size()

...
```

**Comment by octoper** [comment]
> I don't know Go that well, but would it be possible avoiding having to the double Ray: `ray.Ray()`, would be much nicer if users would be able to call `ray()` or `Ray()`, but I don't know if that's possible in the language.

Hey! 
Sadly I don't think that's possible the way Go handles modules.

**Comment by octoper** [comment]
> @freekmurze First of all, thanks for the awesome Ray app. I've been using it every day since I bought it.
> 
> A few days ago I also started a Go adapter (https://github.com/petaki/go-ray), but this is a more complete lib. Thanks @octoper!
> 
> I created a `DefaultRay` instance based on the official `net/http` lib `DefaultClient` idea and I created a wrapper method around it.
> 
> Code:
> 
> - https://github.com/petaki/go-ray/blob/master/ray.go#L22
> - https://github.com/petaki/go-ray/blob/master/ray.go#L165
> 
> After this, I can call the methods on the namespace:
> 
> ```go
> ray.Send()
> ray.Pass()
> ray.Color()
> ray.Size()
> 
> ...
> ```

Hey @petaki 
I like your approach but, can you call something like `ray(...)` ?

**Comment by petaki** [comment]
@octoper Unfortunately, I have no idea, only for the methods.

**Pull request merged**
