### PR TITLE
File path rewritten for remote dev server

### PR DESCRIPTION
**Pull request by SRWieZ**
Can't test but should replace https://github.com/spatie/laravel-ray/pull/23

### CODE REVIEW

**Comment by freekmurze** [comment]
So I can just close the other PR and just take a look at this one, right?

**Comment by freekmurze** [comment]
It seems that both PRs are needed, I'll polish this one first

**Comment by freekmurze** [comment]
Thanks!

**Comment by SRWieZ** [comment]
You're welcome!

**Pull request merged**
