### PR TITLE
Add a method to send data and pass it through

### PR DESCRIPTION
**Pull request by sebastiandedeyne**
The new `pass` method is useful to debug `return` statements.

```php
public function foo() {
    return [
        // …
    ];
}
```

With `ray()->send()`:

```php
public function foo() {
    $data = [
        // …
    ];

    ray()->send($data);

    return $data;
}
```

With `ray()->pass()`:

```php
public function foo() {
    return ray()->pass([
        // …
    ]);
}
```

The name `pass` is under consideration. Any better ideas?

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice, some tests are failing, could you take a look at that?

**Comment by sebastiandedeyne** [comment]
Greener than grass!

**Comment by riasvdv** [comment]
> The name pass is under consideration. Any better ideas?

Maybe just `return`?

**Comment by freekmurze** [comment]
Could you also add this to the docs with an example on why you might want to use this method?

**Comment by janpantel** [comment]
> The name pass is under consideration. Any better ideas?

`tap()` might be a good name, too. This would align with Laravel's helper function.

**Comment by patinthehat** [comment]
> The name pass is under consideration. Any better ideas?

`passthru()` might make it a bit easier to understand what it does.

**Comment by sebastiandedeyne** [comment]
Is `return` allowed, or is that gonna give issues somewhere because it's a reserved word?

`tap` sounds like a good contender.

`passthru` is nice, but a but long and harder to remember (also `thru` vs `through`).

**Comment by sebastiandedeyne** [comment]
Once we've decided on a name, I'll update the docs :)

**Comment by AdrianMrn** [comment]
I'm a fan of `tap` over the other 2 options.

**Comment by mabdullahsari** [comment]
I'm in favor of `tap` / `do`

**Comment by freekmurze** [comment]
I've decided to go with `pass` for now.

**Pull request merged**
