### PR TITLE
Prepare composer, assign type of wordpress-plugin

### PR DESCRIPTION
**Pull request by xewl**
This way when installing this in a composer-based WP project (eg. Bedrock) - it will know it's a plugin and install the folder correctly under the wp-content/plugins directory.

[ref. [daggerhartlab.com/how-to-setup-wordpress-plugin-composer-packagist](https://www.daggerhartlab.com/how-to-setup-wordpress-plugin-composer-packagist/)]

### CODE REVIEW

**Comment by freekmurze** [comment]
This PR seems to have a lot of depencies that I don't need...

**Comment by xewl** [comment]
> This PR seems to have a lot of depencies that I don't need...

Whoah, hmm. I was too quick.

**Comment by freekmurze** [comment]
Thanks!
Meanwhile I fixed some things myself 👍

**Comment by freekmurze** [comment]
O, and the WordPress repo is at spatie/wordpress-ray

**Comment by xewl** [comment]
> spatie/wordpress-ray

You see. Clouded. LMFAO - I'm going to close Github - sorry :x

**Pull request closed without merging**
