### PR TITLE
Config note for docker users (DNS for docker host)

### PR DESCRIPTION
**Pull request by 60days**
host.docker.internal DNS lookup should be used when developing in docker containers.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! 

Can you confirm that this works? Are there any other instructions that we could give to Docker users to ease installation?

Optimistically merging this in already.

**Comment by 60days** [comment]
This is all that was required in my case (I'm using a docker-compose env locally, with separate php, workspace(composer+artisan) and web containers and only ports 80 & 443 exposed. I initially assumed I would need to map the ports of the php container as well, but setting the hostname was enough. I'm on docker 3.0.3, MacOS.

Unfortunately I had to uninstall Ray as I can't seem to deploy to Vapor via Github Actions anymore with it installed. I'll submit a proper bug report if I get time to confirm it would happen for anyone running vapor, but I'll include the error below just in case its obvious (unfortunately a lot of generic traces with no real info!)

```
 Generating optimized autoload files                                          
  > Illuminate\Foundation\ComposerScripts::postAutoloadDump                    
  > @php artisan package:discover --ansi                                       
  Script @php artisan package:discover --ansi handling the post-autoload-dump  
   event returned with error code 1                                            
                                                                               

Exception trace:
  at /tmp/vendor/symfony/process/Process.php:252
 Symfony\Component\Process\Process->mustRun() at /tmp/vendor/laravel/vapor-cli/src/BuildProcess/ExecuteBuildCommands.php:29
 Laravel\VaporCli\BuildProcess\ExecuteBuildCommands->__invoke() at /tmp/vendor/illuminate/support/HigherOrderCollectionProxy.php:60
 Illuminate\Support\HigherOrderCollectionProxy->Illuminate\Support\{closure}() at /tmp/vendor/illuminate/support/Traits/EnumeratesValues.php:202
 Illuminate\Support\Collection->each() at /tmp/vendor/illuminate/support/HigherOrderCollectionProxy.php:61
 Illuminate\Support\HigherOrderCollectionProxy->__call() at /tmp/vendor/laravel/vapor-cli/src/Commands/BuildCommand.php:72
 Laravel\VaporCli\Commands\BuildCommand->handle() at n/a:n/a
 call_user_func_array() at /tmp/vendor/illuminate/container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /tmp/vendor/illuminate/container/Util.php:37
 Illuminate\Container\Util::unwrapIfClosure() at /tmp/vendor/illuminate/container/BoundMethod.php:95
 Illuminate\Container\BoundMethod::callBoundMethod() at /tmp/vendor/illuminate/container/BoundMethod.php:39
 Illuminate\Container\BoundMethod::call() at /tmp/vendor/illuminate/container/Container.php:596
 Illuminate\Container\Container->call() at /tmp/vendor/laravel/vapor-cli/src/Commands/Command.php:72
 Laravel\VaporCli\Commands\Command->execute() at /tmp/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /tmp/vendor/laravel/vapor-cli/src/Commands/Command.php:210
 Laravel\VaporCli\Commands\Command->call() at /tmp/vendor/laravel/vapor-cli/src/Commands/DeployCommand.php:107
 Laravel\VaporCli\Commands\DeployCommand->buildProject() at /tmp/vendor/laravel/vapor-cli/src/Commands/DeployCommand.php:53
 Laravel\VaporCli\Commands\DeployCommand->handle() at n/a:n/a
 call_user_func_array() at /tmp/vendor/illuminate/container/BoundMethod.php:37
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /tmp/vendor/illuminate/container/Util.php:37
 Illuminate\Container\Util::unwrapIfClosure() at /tmp/vendor/illuminate/container/BoundMethod.php:95
 Illuminate\Container\BoundMethod::callBoundMethod() at /tmp/vendor/illuminate/container/BoundMethod.php:39
 Illuminate\Container\BoundMethod::call() at /tmp/vendor/illuminate/container/Container.php:596
 Illuminate\Container\Container->call() at /tmp/vendor/laravel/vapor-cli/src/Commands/Command.php:72
 Laravel\VaporCli\Commands\Command->execute() at /tmp/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /tmp/vendor/symfony/console/Application.php:916
 Symfony\Component\Console\Application->doRunCommand() at /tmp/vendor/symfony/console/Application.php:264
 Symfony\Component\Console\Application->doRun() at /tmp/vendor/symfony/console/Application.php:140
 Symfony\Component\Console\Application->run() at /tmp/vendor/laravel/vapor-cli/vapor:201

deploy [--commit [COMMIT]] [--message [MESSAGE]] [--without-waiting] [--] [<environment>]

Error: Process completed with exit code 1.
```

**Comment by viezel** [comment]
works fine on a mac

**Comment by CNSam** [comment]
This only works to a point on Linux using docker-composer, on macOS and Windows the host.docker.internal is already registered but on Linux we have to add the following:

To enable this in Docker Compose on Linux, add the following lines to the container definition:
```
extra_hosts:
- "host.docker.internal:host-gateway"
```

for eaxmple:

```
services:
  site:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
      - db
    networks:
      - packt-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Pull request merged**
