### PR TITLE
Added to docs for windows PhpStorm links

### PR DESCRIPTION
**Pull request by amacsmith**
I was having issues relating PhpStorm links from Ray to my PhpStorm instance and found a work-around solution for it. I am updating docs because I was asked. Let me know if I did something incorrect.

### CODE REVIEW

**Comment by amacsmith** [comment]
This was created in reference to discussion [#65 ](https://github.com/spatie/laravel-ray/discussions/65#discussioncomment-277747)

**Comment by freekmurze** [comment]
Thanks for posting this. I don't want to maintain that `run_editor.js` file. Where did you find it? Could you replace it with a link?

**Comment by amacsmith** [comment]
Absolutely, will do in a bit.

**Comment by amacsmith** [comment]
@freekmurze I have linked it in the previous paragraph. However, the code shown is just an explanation of a potential bug/issue people may run into using that package. The package is [here](https://github.com/aik099/PhpStormProtocol) created by aik099. The issue is pending at the moment and may potentially get resolved. However, I can go ahead and remove the code explanation as it will probably soon be resolved. Is that what you would like me to do?

**Comment by freekmurze** [comment]
> I can go ahead and remove the code explanation as it will probably soon be resolved. Is that what you would like me to do

👍

**Comment by amacsmith** [comment]
I removed the code and cleaned up the links. Let me know if there is anything else. If not thanks soo much @freekmurze for the amazing tool and glad to be of assistance!

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
