### PR TITLE
Adds the client's hostname in the origin section of a payload

### PR DESCRIPTION
**Pull request by AlexVanderbist**

### CODE REVIEW

**Comment by freekmurze** [comment]
Looking good, maybe fix the tests as well! 👍

**Comment by patinthehat** [comment]
@AlexVanderbist I'm updating the [node-ray](https://github.com/permafrost-dev/node-ray) package to be in sync with this PR - if the hostname can't be determined, what value should be sent?

**Comment by freekmurze** [comment]
@patinthehat @AlexVanderbist how about using the generic string "remote"?

**Comment by patinthehat** [comment]
> how about using the generic string "remote"?

Sounds good, thanks!

**Pull request merged**
